import { toMediaCardData } from './page-data'
import { contentTagHref, resolveContentPolicy } from './policy'
import type {
  ContentKind,
  MediaCardData,
  RenderablePageItem,
  ResolvedPageItem,
  StandardCardData
} from './types'

/**
 * A metadata item is deliberately display-ready.  The card renderer should
 * not know whether a value came from Blog frontmatter or another collection.
 */
export interface TextCardMeta {
  readonly icon: 'earth' | 'time'
  readonly value: string
}

export interface TextCardTag {
  readonly href: string
  readonly label: string
}

export type TextCardSkin = 'blog' | 'plain'

/**
 * The view model for the one text-card visual family.  `skin` only preserves
 * the existing Blog class/interaction contract; it is not a content schema.
 */
export interface TextCardViewData extends StandardCardData {
  readonly draft: boolean
  readonly family: 'text'
  readonly metadata: readonly TextCardMeta[]
  readonly skin: TextCardSkin
  readonly tags: readonly TextCardTag[]
}

/** The view model for the one Media visual family. */
export interface MediaCardViewData {
  readonly data: MediaCardData
  readonly family: 'media'
}

export type ContentCardViewData = TextCardViewData | MediaCardViewData

export interface TextCardProjectionOptions {
  /** Generated by Astro's content renderer at the rendering boundary. */
  readonly readingMinutes?: number | string
  readonly skin?: TextCardSkin
}

/**
 * Project a PageItem into the text-card contract.  Content-specific fields are
 * converted here, once; TextCard.astro only renders the resulting regions.
 */
export function toTextCardViewData(
  item: ResolvedPageItem | RenderablePageItem,
  options: TextCardProjectionOptions = {}
): TextCardViewData {
  const { record } = item
  const metadata: TextCardMeta[] = []

  const readingMinutes =
    options.readingMinutes ?? ('readingMinutes' in item ? item.readingMinutes : undefined)
  if (readingMinutes !== undefined && readingMinutes !== '') {
    metadata.push({ icon: 'time', value: String(readingMinutes) })
  }

  if (record.kind === 'blog' && record.language) {
    metadata.push({ icon: 'earth', value: record.language })
  }

  return {
    ...item.card,
    draft: record.draft,
    family: 'text',
    metadata,
    skin: options.skin ?? (record.kind === 'blog' ? 'blog' : 'plain'),
    tags:
      resolveContentPolicy(record.kind).tags === 'links'
        ? record.tags.map((tag) => ({ href: contentTagHref(record.kind, tag), label: tag }))
        : []
  }
}

/**
 * Select a visual family from page placement, never from the source
 * collection.  This is what lets one content type appear in different card
 * families on different pages without creating another content component.
 */
export function toContentCardViewData(
  item: ResolvedPageItem | RenderablePageItem,
  options: TextCardProjectionOptions = {}
): ContentCardViewData {
  if (item.placement.presentation === 'text') {
    return { ...toTextCardViewData(item, options), family: 'text' }
  }

  return {
    data: toMediaCardData(item),
    family: 'media'
  }
}

/** Keep the public type vocabulary available to callers building adapters. */
export type CardContentType = ContentKind
