/** Generated by scripts/apply-card-crops.mjs (archive-card). Do not edit by hand. */
import type { CardCropRecord } from '@/lib/card-crop/types'

export const cardCropSelectionsGenerated: Readonly<Record<string, CardCropRecord>> = {
  "43935854_p0_master1200.webp": {
    "filename": "43935854_p0_master1200.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 60.78125,
        "y": 28.531624407913057,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 100,
        "y": 32.14264913238833,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.892857142857143,
        "x": 0.06512276785714279,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.892857142857143,
        "x": 0.10714285714285704,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:25:31.931Z"
  },
  "riki32-naruto-7203819.webp": {
    "filename": "riki32-naruto-7203819.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.9523809523809524,
        "x": 0.023809523809523784,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.9523809523809524,
        "x": 0.023809523809523784,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:25:48.066Z"
  },
  "thumb-1920-1083849.webp": {
    "filename": "thumb-1920-1083849.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 0.15625,
        "y": 32.81136806910007,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8311011904761905,
        "x": 0.08444940476190474,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8311011904761905,
        "x": 0.00026390438988095236,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:08:15.919Z"
  },
  "thumb-1920-1100118.webp": {
    "filename": "thumb-1920-1100118.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 92.1875,
        "y": 17.118974644747844,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.9345238095238095,
        "x": 0.032738095238095254,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.9345238095238095,
        "x": 0.060360863095238124,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:08:34.684Z"
  },
  "thumb-1920-1199807.webp": {
    "filename": "thumb-1920-1199807.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 6.067714691162109,
        "y": 0,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.7522321428571428,
        "x": 0.12388392857142859,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.7522321428571428,
        "x": 0.015033846667834692,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:08:50.069Z"
  },
  "thumb-1920-1348996.webp": {
    "filename": "thumb-1920-1348996.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 18.333330154418945,
        "y": 79.53190303705756,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 100,
        "y": 31.77062325999255,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.800595238095238,
        "x": 0.036557533343633014,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.800595238095238,
        "x": 0.19940476190476192,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:09:29.656Z"
  },
  "thumb-1920-1377699.webp": {
    "filename": "thumb-1920-1377699.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 24.94791030883789,
        "y": 63.48286430760655,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 100,
        "y": 0,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.800595238095238,
        "x": 0.04974732115155175,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.800595238095238,
        "x": 0.19940476190476192,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:09:58.194Z"
  },
  "thumb-1920-206280.webp": {
    "filename": "thumb-1920-206280.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 44.375,
        "y": 100,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.08716517857142855,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:10:07.474Z"
  },
  "thumb-1920-432644.webp": {
    "filename": "thumb-1920-432644.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 76.09375,
        "y": 60.76901643911974,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.9858630952380952,
        "x": 0.007068452380952372,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.9858630952380952,
        "x": 0.010757300967261891,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:11:04.887Z"
  },
  "thumb-1920-556375.webp": {
    "filename": "thumb-1920-556375.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 34.01041030883789,
        "y": 58.48983003622183,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.06680616310664585,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:11:16.878Z"
  },
  "thumb-1920-582756.webp": {
    "filename": "thumb-1920-582756.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 0,
        "y": 25.632158899250893,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 0.3125,
        "y": 67.54527723599934,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.84375,
        "x": 0,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.84375,
        "x": 0.00048828125,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:11:26.758Z"
  },
  "thumb-1920-608170.webp": {
    "filename": "thumb-1920-608170.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 100,
        "y": 31.5846069177753,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 48.75,
        "y": 95.2242964614096,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.972470238095238,
        "x": 0.02752976190476192,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.972470238095238,
        "x": 0.013420758928571436,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:11:38.134Z"
  },
  "thumb-1920-672421.webp": {
    "filename": "thumb-1920-672421.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 0,
        "y": 68.25856784619717,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8571428571428572,
        "x": 0.07142857142857141,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8571428571428572,
        "x": 0,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:11:50.047Z"
  },
  "thumb-1920-689823.webp": {
    "filename": "thumb-1920-689823.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 95.15625,
        "y": 38.87433825578166,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.18691406249999998,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:12:33.933Z"
  },
  "thumb-1920-695454.webp": {
    "filename": "thumb-1920-695454.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 95.3125,
        "y": 30.671496238506506,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.18722098214285712,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:12:44.710Z"
  },
  "thumb-1920-704042.webp": {
    "filename": "thumb-1920-704042.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:12:50.983Z"
  },
  "thumb-1920-704341.webp": {
    "filename": "thumb-1920-704341.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 0,
        "y": 0,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 100,
        "y": 0,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.19642857142857142,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:12:55.958Z"
  },
  "thumb-1920-704565.webp": {
    "filename": "thumb-1920-704565.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 100,
        "y": 0,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 0,
        "y": 15.587399036219193,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.816220238095238,
        "x": 0.18377976190476192,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.816220238095238,
        "x": 0,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:13:00.872Z"
  },
  "thumb-1920-705101.webp": {
    "filename": "thumb-1920-705101.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 93.75,
        "y": 96.79019225410983,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.802827380952381,
        "x": 0.1848493303571428,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.802827380952381,
        "x": 0.09858630952380949,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:13:23.386Z"
  },
  "thumb-1920-705691.webp": {
    "filename": "thumb-1920-705691.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 31.171894073486328,
        "y": 13.90916689885767,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 49.609375,
        "y": 100,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 0.9689978370583994,
        "width": 1,
        "x": 0,
        "y": 0.0043121425858030265
      },
      "diagonal-right": {
        "height": 0.9689978370583994,
        "width": 1,
        "x": 0,
        "y": 0.031002162941600575
      }
    },
    "updatedAt": "2026-08-31T17:13:58.341Z"
  },
  "thumb-1920-710137.webp": {
    "filename": "thumb-1920-710137.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 46.09375,
        "y": 9.986068542769578,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8355654761904762,
        "x": 0.0757940383184524,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8355654761904762,
        "x": 0.08221726190476192,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:14:29.242Z"
  },
  "thumb-1920-723809.webp": {
    "filename": "thumb-1920-723809.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 100,
        "y": 0,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 30.651044845581055,
        "y": 100,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.19642857142857142,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.06020740951810564,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:14:49.554Z"
  },
  "thumb-1920-725406.webp": {
    "filename": "thumb-1920-725406.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 0,
        "y": 19.307681602311487,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 53.93227577209473,
        "y": 2.853162440791282,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.10593839883804321,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:15:10.927Z"
  },
  "thumb-1920-769914.webp": {
    "filename": "thumb-1920-769914.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 100,
        "y": 20.237746283300616,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 98.28125,
        "y": 44.363332404569874,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0.10714285714285718,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0.10530133928571432,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:15:31.852Z"
  },
  "thumb-1920-806818.webp": {
    "filename": "thumb-1920-806818.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 46.5625,
        "y": 39.944274171078284,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 0.9896907216494846,
        "width": 1,
        "x": 0,
        "y": 0.004117966409389513
      },
      "diagonal-right": {
        "height": 0.9896907216494846,
        "width": 1,
        "x": 0,
        "y": 0.005154639175257732
      }
    },
    "updatedAt": "2026-08-31T17:15:40.291Z"
  },
  "thumb-1920-888035.webp": {
    "filename": "thumb-1920-888035.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 50.15625,
        "y": 87.09111173028698,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 0,
        "y": 32.88670768921826,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 0.9525159461374911,
        "width": 1,
        "x": 0,
        "y": 0.041354390403467244
      },
      "diagonal-right": {
        "height": 0.9525159461374911,
        "width": 1,
        "x": 0,
        "y": 0.015615941992754243
      }
    },
    "updatedAt": "2026-08-31T17:15:47.282Z"
  },
  "thumb-1920-893435.webp": {
    "filename": "thumb-1920-893435.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 77.96875,
        "y": 42.440791306770706,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 0.8813114754098361,
        "width": 1,
        "x": 0,
        "y": 0.05037234902639671
      },
      "diagonal-right": {
        "height": 0.8813114754098361,
        "width": 1,
        "x": 0,
        "y": 0.05934426229508197
      }
    },
    "updatedAt": "2026-08-31T17:16:56.007Z"
  },
  "thumb-1920-905838.webp": {
    "filename": "thumb-1920-905838.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 89.0625,
        "y": 100,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 0,
        "y": 33.444749903831145,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.17494419642857142,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:17:16.642Z"
  },
  "thumb-1920-916541.webp": {
    "filename": "thumb-1920-916541.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 0,
        "y": 31.167456115909747,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:17:28.446Z"
  },
  "thumb-1920-919724.webp": {
    "filename": "thumb-1920-919724.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 89.21875,
        "y": 0,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.17525111607142857,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:17:37.020Z"
  },
  "thumb-1920-919958.webp": {
    "filename": "thumb-1920-919958.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 27.8125,
        "y": 0,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 0,
        "y": 21.39871830593478,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0.029799107142857155,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:18:11.965Z"
  },
  "thumb-1920-939173.webp": {
    "filename": "thumb-1920-939173.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 80.46875,
        "y": 14.979102814154368,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.15806361607142855,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:18:30.098Z"
  },
  "thumb-1920-949729.webp": {
    "filename": "thumb-1920-949729.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 72.44791030883789,
        "y": 29.74087489551437,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.14230839524950298,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:18:48.959Z"
  },
  "thumb-1920-986446.webp": {
    "filename": "thumb-1920-986446.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 55.468759536743164,
        "y": 51.35692393424357,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 78.77605438232422,
        "y": 0,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.10895649194717406,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.154738678250994,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:19:04.638Z"
  },
  "13534647_p0_master1200.webp": {
    "filename": "13534647_p0_master1200.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 0,
        "y": 77.74867651156313,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 3.7760353088378906,
        "y": 100,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 0.7,
        "width": 1,
        "x": 0,
        "y": 0.2332460295346894
      },
      "diagonal-right": {
        "height": 0.7,
        "width": 1,
        "x": 0,
        "y": 0.3
      }
    },
    "updatedAt": "2026-08-31T17:19:23.350Z"
  },
  "85970602_p0_master1200.webp": {
    "filename": "85970602_p0_master1200.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 34.6875,
        "y": 37.587071607690184,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 0.9905660377358491,
        "width": 1,
        "x": 0,
        "y": 0.0047169811320754715
      },
      "diagonal-right": {
        "height": 0.9905660377358491,
        "width": 1,
        "x": 0,
        "y": 0.0035459501516688858
      }
    },
    "updatedAt": "2026-08-31T17:19:39.575Z"
  },
  "thumb-1920-1110448.webp": {
    "filename": "thumb-1920-1110448.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 36.19791030883789,
        "y": 0,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 56.82289123535156,
        "y": 29.027584285316568,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 0.9518413597733711,
        "width": 1,
        "x": 0,
        "y": 0
      },
      "diagonal-right": {
        "height": 0.9518413597733711,
        "width": 1,
        "x": 0,
        "y": 0.013979289882447071
      }
    },
    "updatedAt": "2026-08-31T17:19:57.624Z"
  },
  "thumb-1920-1305986.webp": {
    "filename": "thumb-1920-1305986.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 0,
        "y": 0,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 6.666669845581055,
        "y": 0,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.734375,
        "x": 0,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.734375,
        "x": 0.017708341777324676,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:20:25.560Z"
  },
  "thumb-1920-1381117.webp": {
    "filename": "thumb-1920-1381117.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.800595238095238,
        "x": 0.09970238095238096,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.800595238095238,
        "x": 0.09970238095238096,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:20:41.502Z"
  },
  "thumb-1920-25430.webp": {
    "filename": "thumb-1920-25430.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 21.5625,
        "y": 39.230983560880446,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 42.65625,
        "y": 72.75564224017828,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 0.9333333333333333,
        "width": 1,
        "x": 0,
        "y": 0.026153989040586963
      },
      "diagonal-right": {
        "height": 0.9333333333333333,
        "width": 1,
        "x": 0,
        "y": 0.04850376149345218
      }
    },
    "updatedAt": "2026-08-31T17:21:06.189Z"
  },
  "thumb-1920-330278.webp": {
    "filename": "thumb-1920-330278.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 6.875,
        "y": 68.61521315129608,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 45.3125,
        "y": 100,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0.007366071428571431,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0.048549107142857165,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:21:33.280Z"
  },
  "thumb-1920-411820.webp": {
    "filename": "thumb-1920-411820.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 0,
        "y": 69.6851490665924,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 45.3125,
        "y": 100,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0.048549107142857165,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:22:05.820Z"
  },
  "thumb-1920-444982.webp": {
    "filename": "thumb-1920-444982.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:22:20.863Z"
  },
  "thumb-1920-476288.webp": {
    "filename": "thumb-1920-476288.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 0,
        "y": 26.339285714285804,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:22:36.946Z"
  },
  "thumb-1920-484717.webp": {
    "filename": "thumb-1920-484717.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 47.8125,
        "y": 0.7829478963499197,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 0,
        "y": 49.330357142857146,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.0939174107142857,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:22:48.124Z"
  },
  "thumb-1920-568874.webp": {
    "filename": "thumb-1920-568874.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 30.15625,
        "y": 26.03510727222064,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.059235491071428566,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8035714285714286,
        "x": 0.09821428571428571,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:22:55.572Z"
  },
  "thumb-1920-655989.webp": {
    "filename": "thumb-1920-655989.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 16.71875,
        "y": 100,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.5267857142857143,
        "x": 0.23660714285714285,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.5267857142857143,
        "x": 0.07911551339285713,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:23:07.240Z"
  },
  "thumb-1920-655990.webp": {
    "filename": "thumb-1920-655990.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 60.78125,
        "y": 71.11173028698829,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.802827380952381,
        "x": 0.1198439825148809,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.802827380952381,
        "x": 0.09858630952380949,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:23:25.096Z"
  },
  "thumb-1920-719184.webp": {
    "filename": "thumb-1920-719184.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 0,
        "y": 76.81805516857095,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 100,
        "y": 1.1160714285714493,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8489583333333334,
        "x": 0,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8489583333333334,
        "x": 0.15104166666666666,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:23:50.633Z"
  },
  "thumb-1920-729590.webp": {
    "filename": "thumb-1920-729590.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 47.8125,
        "y": 82.81136806909993,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.9002976190476191,
        "x": 0.04985119047619045,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.9002976190476191,
        "x": 0.04767020089285712,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:24:08.306Z"
  },
  "thumb-1920-76071.webp": {
    "filename": "thumb-1920-76071.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-right",
    "schemaVersion": 2,
    "selection": "diagonal-right",
    "transforms": {
      "diagonal-left": {
        "x": 50,
        "y": 50,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 47.96875,
        "y": 100,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0.05357142857142859,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0.051395089285714304,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:24:20.163Z"
  },
  "thumb-1920-83606.webp": {
    "filename": "thumb-1920-83606.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 68.90625,
        "y": 77.88799108386766,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0.07382812500000004,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8928571428571428,
        "x": 0.05357142857142859,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:24:49.127Z"
  },
  "thumb-1920-920085.webp": {
    "filename": "thumb-1920-920085.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 48.28125,
        "y": 56.419615491780476,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 50,
        "y": 50,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 1,
        "width": 0.8043154761904762,
        "x": 0.09447893415178572,
        "y": 0
      },
      "diagonal-right": {
        "height": 1,
        "width": 0.8043154761904762,
        "x": 0.09784226190476192,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:25:02.824Z"
  },
  "thumb-1920-934905.webp": {
    "filename": "thumb-1920-934905.webp",
    "fit": "cover",
    "preferredFrame": "diagonal-left",
    "schemaVersion": 2,
    "selection": "diagonal-left",
    "transforms": {
      "diagonal-left": {
        "x": 50.3125,
        "y": 32.16773474505423,
        "zoom": 1
      },
      "diagonal-right": {
        "x": 34.53125,
        "y": 0,
        "zoom": 1
      }
    },
    "cropRects": {
      "diagonal-left": {
        "height": 0.9882352941176471,
        "width": 1,
        "x": 0,
        "y": 0.0037844393817710862
      },
      "diagonal-right": {
        "height": 0.9882352941176471,
        "width": 1,
        "x": 0,
        "y": 0
      }
    },
    "updatedAt": "2026-08-31T17:25:20.345Z"
  }
}
